# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets', 'assets'),  # 包含所有资源文件
        ('src/modules', 'modules'),  # 包含模块文件
    ],
    hiddenimports=[
        'pygame',
        'numpy',
        'pytmx',
        'pyscroll',
        'modules.game',
        'modules.intro_animation',
        'modules.menu',
        'modules.menus.main_menu',
        'modules.menus.map_hero_select_menu',
        'modules.menus.save_menu',
        'modules.player',
        'modules.enemies.enemy',
        'modules.enemies.enemy_manager',
        'modules.enemies.types.bat',
        'modules.enemies.types.ghost',
        'modules.enemies.types.radish',
        'modules.enemies.types.slime',
        'modules.items.item_manager',
        'modules.items.health_supply',
        'modules.items.ammo_supply',
        'modules.items.escape_door',
        'modules.items.teleport_item',
        'modules.weapons.weapon',
        'modules.weapons.types.bullet',
        'modules.weapons.types.fireball',
        'modules.weapons.types.frost_nova',
        'modules.weapons.types.knife',
        'modules.lighting_manager',
        'modules.vision_system',
        'modules.map_manager',
        'modules.save_system',
        'modules.upgrade_system',
        'modules.round_ui',
        'modules.game_result_ui',
        'modules.minimap',
        'modules.resource_manager',
        'modules.utils',
        'modules.components.animation_component',
        'modules.components.health_component',
        'modules.components.movement_component',
        'modules.components.weapon_manager',
        'modules.components.passive_manager',
        'modules.components.progression_system',
        'modules.core.game_state',
        'modules.core.input_manager',
        'modules.core.render_manager',
        'modules.core.scene_manager',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='像素生存游戏',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # 设置为False以隐藏控制台窗口
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,  # 可以在这里添加图标文件路径
) 